### ISSUE TITLE
How to Integrate Knobs with Chapters 

### ISSUE THREAD

**Issue by josefarfetch** [yangshun/react-storybook-addon-chapters#10]

**Comment by josefarfetch** [comment]
Managed to do it... was using the knob decorator inside the function

**Comment by miamollie** [comment]
Hi, can you give an example of how you got `withKnobs` working alongside `withChapters`? What do you mean by 

> inside the function

Thanks!

**Comment by brandonellis** [comment]
You add it to the story the same way you would when using it without the module. 

`storiesOf('Example', module)
	.addDecorator(withKnobs)
	.addWithChapters();`

**Comment by johnnyBira** [comment]
But where to define the inputs for Knobs? In exampled not using Chapters we can define these inside the callback function of the Stroybook add function.
If they are defined outside it wont work, likely because of closure. Any one had any luck on this?

**Comment by johnnyBira** [comment]
Never mind. I realised it is possible the pass a function that returns the Chapters object as the second param of `addWithChapters`, the same way `add` works.
I define my my knobs inputs here and everything is working just fine.
