### ISSUE TITLE
Default Props Value Not Showing Up

### ISSUE THREAD

**Issue by ohearonkg** [yangshun/react-storybook-addon-chapters#2]
Using chapters the default prop values supplied to my component do not show up. 

The first image is when a simple story is added to the story book, and the second with the same component is rendered within a section 

<img width="822" alt="screen shot 2017-03-11 at 7 40 29 pm" src="https://cloud.githubusercontent.com/assets/8875085/23827804/f7722738-0692-11e7-835b-27acb82f7400.png">

<img width="870" alt="screen shot 2017-03-11 at 7 40 42 pm" src="https://cloud.githubusercontent.com/assets/8875085/23827806/fddd71b8-0692-11e7-9cc9-ee8abc5be851.png">

For some reason, the default value fields are not populated.

**Comment by yangshun** [comment]
@ohearonkg Thanks for reporting, have fixed and published v1.0.1
